---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for existing install in {{ mitmproxy_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ mitmproxy_install_dir }}'
  changed_when: false
  register: mitmproxy_binary
- name: Downloading and installing mitproxy
  when: not mitmproxy_binary.stat.exists
  block:
    - name: Downloading {{ mitmproxy_url }} to {{ mitmproxy_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ mitmproxy_url }}'
        dest: '{{ mitmproxy_tmp_archive }}'
        checksum: '{{ mitmproxy_checksum }}'
        mode: '644'
    - name: Mkdir {{ mitmproxy_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ mitmproxy_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ mitmproxy_tmp_archive }} to {{ mitmproxy_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ mitmproxy_tmp_archive }}'
        dest: '{{ mitmproxy_install_dir }}'
        creates: '{{ mitmproxy_installed_exe }}'
  always:
    - name: Rm {{ mitmproxy_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ mitmproxy_tmp_archive }}'
        state: absent
- name: Link {{ mitmproxy_link }} to {{ mitmproxy_installed_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ mitmproxy_installed_exe }}'
    dest: '{{ mitmproxy_link }}'
    state: link
