---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for existing install in {{ mitmproxy_install_dir }}
  become: true
  stat:
    path: '{{ mitmproxy_install_dir }}'
  changed_when: False
  register: mitmproxy_binary
- when: not mitmproxy_binary.stat.exists
  block:
    - name: downloading {{ mitmproxy_url }} to {{ mitmproxy_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ mitmproxy_url }}'
        dest: '{{ mitmproxy_tmp_archive }}'
        checksum: '{{ mitmproxy_checksum }}'
        mode: 0644
    - name: mkdir {{ mitmproxy_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ mitmproxy_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ mitmproxy_tmp_archive }} to {{ mitmproxy_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ mitmproxy_tmp_archive }}'
        dest: '{{ mitmproxy_install_dir }}'
        creates: '{{ mitmproxy_installed_exe }}'
  always:
    - name: rm {{ mitmproxy_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ mitmproxy_tmp_archive }}'
        state: absent
- name: link {{ mitmproxy_link }} to {{ mitmproxy_installed_exe }}
  become: true
  become_user: root
  file:
    src: '{{ mitmproxy_installed_exe }}'
    dest: '{{ mitmproxy_link }}'
    state: link
